# Custom Language File for Launcher Customizer

[ejs.app]
title = "경찰과 도둑"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/neez0611"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaSoopURL = "https://ch.sooplive.co.kr/neez0611"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/neez0611"
supportLink = "https://github.com/CustomLauncherLab/neez0611/issues"

[ejs.welcome]
welcomeHeader = "경찰과 도둑"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."